"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  CheckCircle2,
  Clock,
  Copy,
  Download,
  FileText,
  Loader2,
  Send,
  XCircle,
} from "lucide-react";
import { saveAs } from "file-saver";
import { toast } from "sonner";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { generateQuotationPDFBlob } from "@/components/dashboard/extensions/quotation-templates/pdf-utils";
import { useAuth } from "@/context/AuthContext";
import { hasResourceAction } from "@/lib/role-permissions";
import {
  snaggingQuoteToTemplateData,
  type SnaggingQuoteDoc,
} from "@/lib/snagging/quotation-template-data";
import { snaggingService, type SnaggingQuotation } from "@/modules/snagging";
import { ActionType, ResourceType, type SnaggingTask } from "@/types/types";

import { EmptyState } from "@/components/ui/empty-state";

import { YallaClassicTemplate } from "@/components/dashboard/extensions/quotation-templates/templates/YallaClassicTemplate";

import {
  DataState,
  QuotationStatusBadge,
  SectionCard,
  SubHeading,
  SubmitButton,
  formatGstDateTime,
} from "./shared";

/** Builds the document snapshot the shared quotation template renders from. */
function toDocData(q: SnaggingQuotation): SnaggingQuoteDoc {
  const s = (q.property_snapshot ?? {}) as Record<string, unknown>;
  return {
    quote_number: q.quote_number,
    status: q.status,
    created_at: q.created_at,
    sent_at: q.sent_at,
    currency: q.currency,
    subtotal: q.subtotal,
    tax_rate: q.tax_rate,
    tax_amount: q.tax_amount,
    total: q.total,
    lines: q.lines,
    scope_of_work: q.scope_of_work,
    terms: q.terms,
    property: {
      unit_label: s.unit_label as string,
      building_name: s.building_name as string,
      community: s.community as string,
      developer_name: s.developer_name as string,
      property_type: s.property_type as string,
      bedrooms: s.bedrooms as number,
      built_up_area_sqft: s.built_up_area_sqft as number,
      client_name: s.client_name as string,
      client_email: s.client_email as string,
      client_phone: s.client_phone as string,
      client_ref: s.client_ref as string,
    },
  };
}

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onloadend = () => {
      const s = String(r.result);
      resolve(s.slice(s.indexOf(",") + 1));
    };
    r.onerror = reject;
    r.readAsDataURL(blob);
  });
}

/**
 * Quotation for a job (F1-F6, FR-2.06). A job stays a draft until its
 * quotation is approved — by the client through the emailed link, or by a
 * coordinator recording the client's decision here.
 */
export function QuotationPanel({
  task,
}: {
  task: SnaggingTask;
  /**
   * Part of the panel's contract with the job screen, but nothing here
   * moves the job any more: the client approves or rejects through the
   * emailed link, and the job screen reloads on its own.
   */
  onChanged: () => void;
}) {
  const { userProfile } = useAuth();
  const canEdit = hasResourceAction(
    userProfile,
    ResourceType.SNAGGING,
    ActionType.EDIT,
  );
  const [quote, setQuote] = useState<SnaggingQuotation | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [working, setWorking] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [sendOpen, setSendOpen] = useState(false);
  const [regenOpen, setRegenOpen] = useState(false);
  const [recipient, setRecipient] = useState("");
  const [approvalUrl, setApprovalUrl] = useState<string | null>(null);
  const busy = working || downloading;
  /** Guards the auto-generate so a re-render can never number a second document. */
  const autoGenerated = useRef(false);
  /**
   * True while the automatic generation is in flight. There is no Generate
   * button any more, so this is the only thing that tells the coordinator a
   * document is being numbered rather than the tab simply being slow.
   */
  const [generating, setGenerating] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      // The API answers an absent quotation with null, so only a thrown
      // error is a failure. Swallowing it used to make "the server is
      // down" look identical to "no quotation yet" — and the panel then
      // offered Generate, which numbers a second financial document
      // against a job that already has one.
      // Ask for the preview too: a job that has never been quoted still
      // opens on the document it would be quoted, rather than on a button.
      const current = await snaggingService.getQuotation(task.id, {
        preview: true,
      });

      /*
        Open the tab, get a quotation.

        Generating writes a numbered document and an audit row, so the
        conditions are deliberately narrow:

          - the server came back with a preview, meaning no quotation
            exists at all. A job that already has one of any status is
            never touched, so this can neither renumber a sent quote nor
            mint a second one;
          - the caller may edit;
          - once per mount;
          - and the job is an initial inspection.

        This was once limited to initial inspections, because a de-snag
        round is free — it re-checks work already paid for — and nothing
        server-side stops a round being quoted. Rounds kept a manual
        Generate button so raising a charge stayed a decision. That button
        is gone, so the restriction would now leave a round showing a
        preview with no way to act on it; the visit-type judgement belongs
        on the server, the only place it can actually be enforced.

        If it fails, the preview stays on screen, labelled as a preview,
        rather than the tab collapsing to an error.
      */
      if (current?.preview && canEdit && !autoGenerated.current) {
        autoGenerated.current = true;
        setGenerating(true);
        try {
          await snaggingService.quotationAction(task.id, "generate");
          setQuote(await snaggingService.getQuotation(task.id));
          return;
        } catch {
          // Fall through and show the preview; the reason surfaces on the
          // next load, or when the coordinator regenerates.
        } finally {
          setGenerating(false);
        }
      }

      setQuote(current);
    } catch (err) {
      setQuote(null);
      setError(
        err instanceof Error ? err.message : "Could not load the quotation",
      );
    } finally {
      setLoading(false);
    }
  }, [task.id, canEdit]);

  useEffect(() => {
    void load();
  }, [load]);

  /**
   * Generate (or regenerate) the quotation. Approve and reject are the
   * client's decisions, recorded through the emailed link — this panel
   * never drives them, so it only knows this one action.
   */
  async function run() {
    if (working) return;
    setWorking(true);
    try {
      await snaggingService.quotationAction(task.id, "generate");
      await load();
      toast.success("Quotation generated");
    } catch (error) {
      toast.error(
        error instanceof Error
          ? error.message
          : "Could not update the quotation",
      );
    } finally {
      setWorking(false);
    }
  }

  async function makePdfBase64(): Promise<string | null> {
    if (!quote) return null;
    const blob = await generateQuotationPDFBlob(
      "yalla-classic",
      snaggingQuoteToTemplateData(toDocData(quote)),
      { scale: 2 },
      "without",
    );
    return blobToBase64(blob);
  }

  async function download() {
    if (!quote) return;
    setDownloading(true);
    const t = toast.loading("Preparing the PDF…");
    try {
      const blob = await generateQuotationPDFBlob(
        "yalla-classic",
        snaggingQuoteToTemplateData(toDocData(quote)),
        { scale: 2 },
        "without",
      );
      saveAs(blob, `Quotation-${quote.quote_number}.pdf`);
      toast.success("PDF downloaded", { id: t });
    } catch (e) {
      toast.error(
        e instanceof Error ? e.message : "Could not generate the PDF",
        { id: t },
      );
    } finally {
      setDownloading(false);
    }
  }

  async function sendToClient() {
    if (!quote || !recipient.trim()) return;
    setWorking(true);
    try {
      const pdf_base64 = await makePdfBase64();
      const res = (await snaggingService.quotationAction(task.id, "send", {
        sent_to: recipient.trim(),
        pdf_base64,
      })) as SnaggingQuotation;
      setApprovalUrl(res.approval_url ?? null);
      setSendOpen(false);
      toast.success("Quotation emailed to the client");
      await load();
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : "Could not send the quotation",
      );
    } finally {
      setWorking(false);
    }
  }

  const isPreview = Boolean(quote?.preview);
  const isDecided =
    quote?.status === "approved" || quote?.status === "rejected";

  return (
    <SectionCard
      title="Quotation"
      icon={<FileText />}
      description={
        error
          ? "The quotation could not be loaded."
          : generating
            ? "Raising a quotation for this job."
            : loading
              ? "Loading the quotation."
              : quote
                ? `Quotation ${quote.quote_number}`
                : task.status === "draft"
                  ? "This job is a draft. Generate and send a quotation to the client to proceed."
                  : "No quotation on this job."
      }
      // The status belongs in the header as a badge, not as a raw
      // lowercase word appended to the subtitle.
      action={quote ? <QuotationStatusBadge status={quote.status} /> : null}
      bodyClassName="border-t"
    >
      <div className="space-y-4 p-5">
        <DataState
          loading={loading || generating}
          error={error}
          onRetry={() => void load()}
          retrying={loading}
          errorTitle="Could not load the quotation"
          isEmpty={!quote}
          skeleton={
            <div className="space-y-4">
              {generating ? (
                <p className="text-muted-foreground flex items-center gap-2 text-sm">
                  <Loader2 className="size-3.5 animate-spin" />
                  Generating the quotation…
                </p>
              ) : null}

              {/* The quote number and date sit above the table. */}
              <div className="flex items-start justify-between gap-4">
                <Skeleton className="h-4 w-40" />
                <Skeleton className="h-4 w-24" />
              </div>

              <div className="overflow-hidden rounded-lg border">
                <div className="bg-muted/50 flex items-center gap-4 border-b px-4 py-2.5">
                  <Skeleton className="h-3 flex-1" />
                  <Skeleton className="h-3 w-14" />
                  <Skeleton className="h-3 w-16" />
                  <Skeleton className="h-3 w-20" />
                </div>
                {Array.from({ length: 2 }).map((_, index) => (
                  <div
                    key={index}
                    className="flex items-center gap-4 border-b px-4 py-3.5"
                  >
                    <Skeleton className="h-4 flex-1" />
                    <Skeleton className="h-4 w-14" />
                    <Skeleton className="h-4 w-16" />
                    <Skeleton className="h-4 w-20" />
                  </div>
                ))}
                {/* Totals are right-aligned under the table, and the grand
                    total sits on a filled band. */}
                <div className="space-y-2.5 px-4 py-3">
                  {[0, 1].map((index) => (
                    <div key={index} className="flex justify-end gap-4">
                      <Skeleton className="h-3 w-20" />
                      <Skeleton className="h-3 w-20" />
                    </div>
                  ))}
                  <div className="flex justify-end">
                    <Skeleton className="h-8 w-56 rounded-md" />
                  </div>
                </div>
              </div>
            </div>
          }
          empty={
            <EmptyState
              icon={<FileText className="size-6" />}
              title="No quotation yet"
              description={
                task.status === "draft"
                  ? "This job stays a draft until a quotation is generated, sent, and approved by the client."
                  : "Nothing has been quoted against this job."
              }
              // No Generate action: the quotation is raised automatically
              // when the tab opens, so a button here would be a second
              // way to number the same document.
            />
          }
        >
          {quote ? (
            <div className="space-y-5">
              {/*
                What you can do with the document, above the document.

                The tab opens on the quotation as the client will receive
                it, so the controls belong at the top where they are read
                before the page is scrolled — not at the foot of an A4
                sheet somebody has to reach the bottom of first.
              */}
              {canEdit ? (
                <div className="flex flex-wrap items-center justify-end gap-2 pb-2">
                  {isPreview ? (
                    /*
                      A preview still on screen means the automatic
                      generation did not go through. Download and Send
                      would both promise a document that does not exist,
                      so the panel states what it is rather than offering
                      an action.
                    */
                    <p className="text-muted-foreground text-xs">
                      Preview only — this quotation has not been numbered yet.
                    </p>
                  ) : (
                    <>
                      <SubmitButton
                        variant="outline"
                        size="sm"
                        onClick={() => void download()}
                        disabled={busy}
                        pending={downloading}
                        pendingLabel="Preparing…"
                        icon={<Download className="size-4" />}
                      >
                        Download PDF
                      </SubmitButton>
                      {!isDecided ? (
                        <>
                          {quote.status !== "draft" ? null : (
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => setRegenOpen(true)}
                              disabled={busy}
                            >
                              <FileText className="size-4" /> Regenerate
                            </Button>
                          )}
                          <Button
                            size="sm"
                            onClick={() => {
                              const s = (quote.property_snapshot ??
                                {}) as Record<string, unknown>;
                              setRecipient(
                                (s.client_email as string) ??
                                  quote.sent_to ??
                                  "",
                              );
                              setSendOpen(true);
                            }}
                            disabled={busy}
                          >
                            <Send className="size-4" />{" "}
                            {quote.status === "sent"
                              ? "Resend to client"
                              : "Send to client"}
                          </Button>
                        </>
                      ) : (
                        <Badge
                          variant="secondary"
                          className="bg-muted border-0"
                        >
                          {quote.status === "approved"
                            ? "Approved by client — locked"
                            : "Rejected by client"}
                        </Badge>
                      )}
                    </>
                  )}
                </div>
              ) : null}

              {/* Where it stands with the client. */}
              {quote.status === "sent" ? (
                <Alert>
                  <Clock />
                  <AlertTitle>Awaiting the client&apos;s decision</AlertTitle>
                  <AlertDescription>
                    Sent to {quote.sent_to}
                    {quote.sent_at
                      ? ` on ${formatGstDateTime(quote.sent_at)}`
                      : ""}
                    .
                  </AlertDescription>
                </Alert>
              ) : null}
              {quote.status === "approved" ? (
                <Alert className="border-success/30 [&>svg]:text-success">
                  <CheckCircle2 />
                  <AlertTitle>Approved by the client</AlertTitle>
                  <AlertDescription>
                    {quote.approved_by_name
                      ? `${quote.approved_by_name} approved this`
                      : "Approved"}
                    {quote.decided_at
                      ? ` on ${formatGstDateTime(quote.decided_at)}`
                      : ""}
                    . Inspector assignment is unlocked.
                  </AlertDescription>
                </Alert>
              ) : null}
              {quote.status === "rejected" ? (
                <Alert variant="destructive" className="border-destructive/30">
                  <XCircle />
                  <AlertTitle>Rejected by the client</AlertTitle>
                  <AlertDescription>
                    {quote.approved_by_name
                      ? `${quote.approved_by_name}: `
                      : ""}
                    {quote.rejected_reason || "No reason was given."}
                  </AlertDescription>
                </Alert>
              ) : null}

              {approvalUrl ? (
                <div className="space-y-1.5">
                  <p className="text-muted-foreground text-xs font-medium">
                    Client approval link
                  </p>
                  <div className="flex items-center gap-2 rounded-md border p-2">
                    <code className="text-muted-foreground min-w-0 flex-1 truncate font-mono text-xs">
                      {approvalUrl}
                    </code>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => {
                        void navigator.clipboard.writeText(approvalUrl);
                        toast.success("Client link copied");
                      }}
                    >
                      <Copy className="size-3.5" /> Copy
                    </Button>
                  </div>
                </div>
              ) : null}

              {/*
                The quotation as the client receives it — rendered from the
                same YallaClassicTemplate the PDF is built from, so what is
                approved on screen is what lands in their inbox. The figures
                used to be shown as a separate table above this, which meant
                reading the same totals twice in two different shapes.
              */}
              <div className="space-y-2">
                {/* <SubHeading>
                  {isPreview
                    ? "Draft preview — not yet generated"
                    : "Document preview"}
                </SubHeading> */}
                <div className="bg-muted/40 overflow-x-auto rounded-lg border p-4">
                  <div className="mx-auto w-fit bg-white shadow-sm">
                    <YallaClassicTemplate
                      data={snaggingQuoteToTemplateData(toDocData(quote))}
                      hideDiscount
                    />
                  </div>
                </div>
                <p className="text-muted-foreground text-xs">
                  {isPreview
                    ? "Priced by the same rules the generated quotation uses, but nothing is saved until you generate it."
                    : "Rendered from the same template as the PDF. Download it for the exact file the client is sent."}
                </p>
              </div>
            </div>
          ) : null}
        </DataState>
      </div>

      <Dialog open={regenOpen} onOpenChange={setRegenOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Regenerate this quotation?</DialogTitle>
            <DialogDescription>
              This rebuilds the quotation from the current pricing, scope and
              terms, replacing the existing draft figures. Only draft quotations
              can be regenerated.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setRegenOpen(false)}
              disabled={working}
            >
              Cancel
            </Button>
            <SubmitButton
              onClick={async () => {
                setRegenOpen(false);
                await run();
              }}
              pending={working}
              pendingLabel="Regenerating…"
              icon={<FileText className="size-4" />}
            >
              Regenerate
            </SubmitButton>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={sendOpen} onOpenChange={setSendOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Send quotation to the client</DialogTitle>
            <DialogDescription>
              Emails the PDF and a secure approve/reject link to the client via
              Resend. The job stays a draft until the client approves.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-2 py-2">
            <Label htmlFor="quote-recipient">Client email</Label>
            <Input
              id="quote-recipient"
              type="email"
              value={recipient}
              onChange={(e) => setRecipient(e.target.value)}
              placeholder="client@email.com"
            />
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setSendOpen(false)}
              disabled={working}
            >
              Cancel
            </Button>
            <SubmitButton
              onClick={() => void sendToClient()}
              disabled={recipient.trim().length < 3}
              pending={working}
              pendingLabel="Sending…"
              icon={<Send className="size-4" />}
            >
              Send quotation
            </SubmitButton>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </SectionCard>
  );
}
