-- =====================================================================
-- AMC rate card and proposal versions
-- (BRD v0.3 Phase 4: DEV-349, 350, 363, 364, 365, 366, 367, 368)
--
-- NOT APPLIED. Branch amc-hardening, 7 Oct 2026.
-- SAFE BEFORE CODE DEPLOY. Checked against origin/main, 7 Oct 2026:
--   * amc_rate_card_versions and amc_submission_versions are new;
--   * amc_submissions (LIVE: main reads and writes it) only gains nullable
--     columns, or columns with a constant default (current_version = 1,
--     below_floor = false). Live main selects `*` and maps the fields it
--     knows, inserts without these columns (defaults apply) and updates
--     only its own fields, so it is unaffected. No existing row changes.
-- Apply after 20261007130000 (enquiry_id references amc_enquiries).
-- Idempotent: safe to run twice.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Rate card (DEV-349, BRD 5.3): the whole card as one versioned
--    document, like Snagging's pricing card with its change log, made
--    effective-dated. A proposal line records the version it was priced
--    from, so an old proposal keeps the rate of its day.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.amc_rate_card_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version_no bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  effective_from date NOT NULL,
  /* Rates, packages and promotions (lib/amc/rate-card.ts checks the shape). */
  card jsonb NOT NULL CHECK (jsonb_typeof(card) = 'object'),
  reason text NOT NULL CHECK (length(trim(reason)) > 0),
  changed_by uuid REFERENCES public.user_profile(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_amc_rate_card_effective ON public.amc_rate_card_versions (effective_from DESC, version_no DESC);
CREATE INDEX IF NOT EXISTS idx_amc_rate_card_changed_by ON public.amc_rate_card_versions (changed_by) WHERE changed_by IS NOT NULL;

/* A published card is history: it is replaced by a newer version, never edited. */
CREATE OR REPLACE FUNCTION public.amc_history_row_locked()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION '% rows are history and cannot be changed or deleted', TG_TABLE_NAME USING ERRCODE = 'check_violation';
END;
$$;
REVOKE ALL ON FUNCTION public.amc_history_row_locked() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS amc_rate_card_versions_locked ON public.amc_rate_card_versions;
CREATE TRIGGER amc_rate_card_versions_locked
  BEFORE UPDATE OR DELETE ON public.amc_rate_card_versions
  FOR EACH ROW EXECUTE FUNCTION public.amc_history_row_locked();

-- ---------------------------------------------------------------------
-- 2. The proposal header (DEV-350, 365, 366): links, payment plan,
--    validity, the version in progress, and what priced it.
-- ---------------------------------------------------------------------
ALTER TABLE public.amc_submissions
  ADD COLUMN IF NOT EXISTS enquiry_id uuid REFERENCES public.amc_enquiries(id) ON DELETE SET NULL,
  /* The full BRD 5.2 type; `property->>unitType` stays the rate model (villa, apartment, office) live main reads. */
  ADD COLUMN IF NOT EXISTS property_type text CHECK (property_type IS NULL OR property_type IN ('villa', 'apartment', 'townhouse', 'restaurant', 'clinic', 'shop', 'office', 'warehouse', 'other')),
  /* Replaces monthly/quarterly/annual (issue #8). `customer->>paymentTerms` keeps a value live main can print. */
  ADD COLUMN IF NOT EXISTS payment_plan text CHECK (payment_plan IS NULL OR payment_plan IN ('single', 'fifty_fifty', 'quarterly', 'monthly', 'custom')),
  ADD COLUMN IF NOT EXISTS payment_plan_custom jsonb CHECK (payment_plan_custom IS NULL OR jsonb_typeof(payment_plan_custom) = 'array'),
  ADD COLUMN IF NOT EXISTS valid_until date,
  /* V1, V2, … The row is always the active version; earlier ones are locked in amc_submission_versions. */
  ADD COLUMN IF NOT EXISTS current_version integer NOT NULL DEFAULT 1 CHECK (current_version >= 1),
  ADD COLUMN IF NOT EXISTS version_reason text CHECK (version_reason IS NULL OR version_reason IN ('scope_up', 'scope_down', 'discount', 'price_correction', 'frequency', 'duration', 'payment_plan', 'other')),
  ADD COLUMN IF NOT EXISTS version_summary text,
  ADD COLUMN IF NOT EXISTS version_started_at timestamptz,
  ADD COLUMN IF NOT EXISTS version_started_by uuid REFERENCES public.user_profile(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS rate_card_version_id uuid REFERENCES public.amc_rate_card_versions(id) ON DELETE RESTRICT,
  /* A discounted line under its floor rate: an approval trigger (BRD 5.3, 5.5). */
  ADD COLUMN IF NOT EXISTS below_floor boolean NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS idx_amc_submissions_enquiry ON public.amc_submissions (enquiry_id) WHERE enquiry_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_amc_submissions_version_started_by ON public.amc_submissions (version_started_by) WHERE version_started_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_amc_submissions_rate_card ON public.amc_submissions (rate_card_version_id) WHERE rate_card_version_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- 3. Locked versions (DEV-367, BRD 5.4): an edit after sharing creates
--    V(n+1); V(n) is kept exactly, with its own wording snapshot and the
--    PDF the server printed (fixes the overwrite, issue #2).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.amc_submission_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL REFERENCES public.amc_submissions(id) ON DELETE RESTRICT,
  version_no integer NOT NULL CHECK (version_no >= 1),
  /* Why this version was made (null for V1). */
  reason text CHECK (reason IS NULL OR reason IN ('scope_up', 'scope_down', 'discount', 'price_correction', 'frequency', 'duration', 'payment_plan', 'other')),
  summary text,
  started_at timestamptz NOT NULL,
  started_by uuid REFERENCES public.user_profile(id) ON DELETE SET NULL,
  locked_at timestamptz NOT NULL DEFAULT now(),
  locked_by uuid REFERENCES public.user_profile(id) ON DELETE SET NULL,
  status_at_lock text NOT NULL,
  final_price numeric NOT NULL,
  discount_percent numeric NOT NULL DEFAULT 0,
  payment_plan text,
  valid_until date,
  /* Everything the document renders from: property, customer, services, options, settings snapshot. */
  snapshot jsonb NOT NULL CHECK (jsonb_typeof(snapshot) = 'object'),
  content_sha256 text NOT NULL,
  storage_path text NOT NULL UNIQUE,
  content_type text NOT NULL CHECK (content_type IN ('application/pdf', 'text/html')),
  byte_size integer NOT NULL CHECK (byte_size > 0),
  file_sha256 text NOT NULL,
  UNIQUE (submission_id, version_no)
);
CREATE INDEX IF NOT EXISTS idx_amc_submission_versions_started_by ON public.amc_submission_versions (started_by) WHERE started_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_amc_submission_versions_locked_by ON public.amc_submission_versions (locked_by) WHERE locked_by IS NOT NULL;

DROP TRIGGER IF EXISTS amc_submission_versions_locked ON public.amc_submission_versions;
CREATE TRIGGER amc_submission_versions_locked
  BEFORE UPDATE OR DELETE ON public.amc_submission_versions
  FOR EACH ROW EXECUTE FUNCTION public.amc_history_row_locked();

/*
  Locks the active version and opens the next one, in one transaction: the
  version row is written and the proposal moves to V(n+1) as a draft, or
  neither happens. Only from the expected version and a shared status, so
  two people revising at once cannot both succeed. The client's link stops
  working (it showed the old version); the new version takes the current
  wording until it is sent, while the old wording stays in the snapshot.
*/
CREATE OR REPLACE FUNCTION public.amc_lock_proposal_version(
  p_submission_id uuid,
  p_expected_version integer,
  p_reason text,
  p_summary text,
  p_actor uuid,
  p_snapshot jsonb,
  p_content_sha256 text,
  p_storage_path text,
  p_content_type text,
  p_byte_size integer,
  p_file_sha256 text
)
RETURNS integer
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  s public.amc_submissions%ROWTYPE;
BEGIN
  SELECT * INTO s FROM public.amc_submissions WHERE id = p_submission_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'amc_version: proposal not found' USING ERRCODE = 'no_data_found';
  END IF;
  IF s.current_version <> p_expected_version THEN
    RAISE EXCEPTION 'amc_version: the proposal is already at version %', s.current_version USING ERRCODE = 'serialization_failure';
  END IF;
  IF s.status NOT IN ('proposal_sent', 'proposal_rejected', 'proposal_approved') THEN
    RAISE EXCEPTION 'amc_version: a proposal that is % has not been shared, so it is edited in place', s.status USING ERRCODE = 'check_violation';
  END IF;

  INSERT INTO public.amc_submission_versions (
    submission_id, version_no, reason, summary, started_at, started_by, locked_by, status_at_lock,
    final_price, discount_percent, payment_plan, valid_until, snapshot,
    content_sha256, storage_path, content_type, byte_size, file_sha256
  ) VALUES (
    s.id, s.current_version, s.version_reason, s.version_summary,
    COALESCE(s.version_started_at, s.created_at), COALESCE(s.version_started_by, s.owner_id), p_actor, s.status,
    s.final_price, COALESCE(s.discount_percent, 0), s.payment_plan, s.valid_until, p_snapshot,
    p_content_sha256, p_storage_path, p_content_type, p_byte_size, p_file_sha256
  );

  UPDATE public.amc_submissions SET
    current_version = s.current_version + 1,
    status = 'draft',
    version_reason = p_reason,
    version_summary = p_summary,
    version_started_at = now(),
    version_started_by = p_actor,
    settings_snapshot = NULL,
    proposal_token_hash = NULL,
    proposal_token_hint = NULL,
    proposal_token_expires_at = NULL,
    proposal_sent_at = NULL,
    client_decision = NULL,
    client_decided_at = NULL,
    client_decided_by_name = NULL,
    client_rejected_reason = NULL,
    submitted_at = NULL,
    decided_at = NULL,
    sent_back_reason = NULL,
    valid_until = NULL,
    updated_at = now()
  WHERE id = s.id;

  RETURN s.current_version + 1;
END;
$$;
REVOKE ALL ON FUNCTION public.amc_lock_proposal_version(uuid, integer, text, text, uuid, jsonb, text, text, text, integer, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.amc_lock_proposal_version(uuid, integer, text, text, uuid, jsonb, text, text, text, integer, text) TO service_role;

-- ---------------------------------------------------------------------
-- 4. Server-only, like every AMC table.
-- ---------------------------------------------------------------------
ALTER TABLE public.amc_rate_card_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amc_submission_versions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.amc_rate_card_versions, public.amc_submission_versions FROM anon, authenticated;

-- ---------------------------------------------------------------------
-- Rollback (only before any version is locked or card published):
--   DROP FUNCTION IF EXISTS public.amc_lock_proposal_version(uuid, integer, text, text, uuid, jsonb, text, text, text, integer, text);
--   DROP TABLE IF EXISTS public.amc_submission_versions;
--   ALTER TABLE public.amc_submissions DROP COLUMN IF EXISTS enquiry_id, DROP COLUMN IF EXISTS property_type,
--     DROP COLUMN IF EXISTS payment_plan, DROP COLUMN IF EXISTS payment_plan_custom, DROP COLUMN IF EXISTS valid_until,
--     DROP COLUMN IF EXISTS current_version, DROP COLUMN IF EXISTS version_reason, DROP COLUMN IF EXISTS version_summary,
--     DROP COLUMN IF EXISTS version_started_at, DROP COLUMN IF EXISTS version_started_by,
--     DROP COLUMN IF EXISTS rate_card_version_id, DROP COLUMN IF EXISTS below_floor;
--   DROP TABLE IF EXISTS public.amc_rate_card_versions;
--   DROP FUNCTION IF EXISTS public.amc_history_row_locked();
-- ---------------------------------------------------------------------
